services:
  db:
    image: postgres:16
    container_name: dsf_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword # CHANGE THIS!
      POSTGRES_DB: dsf_data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Automatically run our schema script on first startup
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
